name: extended_masked_text
description: A small set of custom TextEditingControllers that allows masked text inputs for flutter apps
version: 2.1.0
homepage: https://github.com/LeandroNovak/extended_masked_text

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  decimal: ^1.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter